// crates/ahcl-kit-materials/src/dependencies.rs - Dependency documentation generation.
//
// Copyright (C) 2026 Aperip Daedalus Foundation. All rights reserved.
//
// The AHCL-covered material identified below forms part of
// AHCL Kit and is provided under version 1.2 of the
// Aperip Heimdall Commons License (AHCL). The applicable version is also subject
// to the AHCL provisions concerning Continuous AHCL Licensing Segments and
// migration to later official versions.
//
// AHCL-covered portions: the whole file
//
// Subject to Section 3.1 of AHCL, after having a reasonable opportunity to
// read AHCL, all applicable Additional Restrictions, and all version notices,
// a person accepts the corresponding terms by engaging in Use of the
// AHCL-covered material identified above. Any separate or affirmative assent
// required by applicable mandatory law must still be obtained.
//
// Official AHCL text and public notices:          https://ahcl.aperip.com
// Applicable LICENSE:                             LICENSE
// Paths below are relative to the directory containing that LICENSE.
// AHCL Materials Directory:                       .ahcl/
// Repository official or recognized AHCL copy:   .ahcl/AHCL-1.2.md
// Project canonical repository:                   https://github.com/Aperip-Daedalus-Foundation/ahcl-kit
// AHCL origin and project notice:                 .ahcl/AHCL-PROJECT-NOTICE.md
// AHCL Version Adoption records:                  .ahcl/AHCL-VERSION-ADOPTION.md
// Complete Corresponding Source and history:      .ahcl/AHCL-SOURCE.md
// Dependencies, Referenced Materials, and licenses:
//                                                    .ahcl/AHCL-DEPENDENCIES.md
//
// SPDX-License-Identifier: LicenseRef-AHCL-1.2

use crate::{LayoutPolicy, MaterialsError, MaterialsErrorCode};
use ahcl_kit_config::EffectiveConfig;
pub(crate) use ahcl_kit_core::sha256_hex;
use ahcl_kit_core::{
    ChangePlan, DependencyEdge, DependencyKind, LockfileEvidence, ProjectView, ResolvedGraph,
    ResolvedPackage,
};
use ahcl_kit_core::{PackageDirectoryInput, assign_package_directories};
use std::collections::{BTreeMap, BTreeSet};
use url::Url;

pub struct DependencyMaterialGenerator;

impl DependencyMaterialGenerator {
    pub fn plan_document(
        view: &dyn ProjectView,
        config: &EffectiveConfig,
        graph: &ResolvedGraph,
    ) -> Result<ChangePlan, MaterialsError> {
        let layout = LayoutPolicy::from_config(config)?;
        let mut desired = ChangePlan::new();
        desired
            .write(
                layout.dependencies_path()?,
                render_document(config, graph)?.into_bytes(),
            )
            .map_err(MaterialsError::from_plan)?;
        desired.compare(view).map_err(MaterialsError::from_plan)
    }
}

pub(crate) fn render_document(
    config: &EffectiveConfig,
    graph: &ResolvedGraph,
) -> Result<String, MaterialsError> {
    let mut rendered = dependency_preamble(config)?;
    render_lockfiles(&mut rendered, graph)?;
    render_dependency_groups(&mut rendered, config, graph)?;
    rendered.push_str(
        "\nAHCL Kit reports declared metadata and retained evidence without selecting or interpreting legal terms.\n",
    );
    Ok(rendered)
}

fn dependency_preamble(config: &EffectiveConfig) -> Result<String, MaterialsError> {
    let layout = LayoutPolicy::from_config(config)?;
    let mut rendered =
        String::from("# AHCL Dependencies and Referenced Materials\n\nGenerated by AHCL Kit for ");
    rendered.push_str(&inline(config.project().name()));
    rendered.push_str(".\n\nConfiguration summary:\n- AHCL version: ");
    rendered.push_str(config.license().version().as_str());
    rendered.push_str("\n- Materials directory: `");
    rendered.push_str(layout.materials_directory().as_str());
    rendered.push_str("`\n- Ecosystem adapters: ");
    push_adapter_names(&mut rendered, config);
    for line in config.adapter_summary_lines() {
        rendered.push_str(&line);
        rendered.push('\n');
    }
    rendered.push_str("- Strict license files: ");
    rendered.push_str(strict_license_label(
        config.generation().strict_license_files(),
    ));
    rendered.push_str("\n\n## Contributing Lockfiles\n\n");
    Ok(rendered)
}

fn push_adapter_names(rendered: &mut String, config: &EffectiveConfig) {
    let adapters = config.adapter_names();
    if adapters.is_empty() {
        rendered.push_str("None.\n");
    } else {
        rendered.push_str(&adapters.join(", "));
        rendered.push('\n');
    }
}

fn strict_license_label(strict: bool) -> &'static str {
    if strict { "true" } else { "false" }
}

fn render_dependency_groups(
    rendered: &mut String,
    config: &EffectiveConfig,
    graph: &ResolvedGraph,
) -> Result<(), MaterialsError> {
    let directories = package_directories(graph);
    let groups = dependency_groups(graph);
    if groups.is_empty() {
        rendered.push_str("\n## Dependencies and Referenced Materials\n\nNone.\n");
        return Ok(());
    }
    let mut context = PackageRender {
        rendered,
        config,
        graph,
        directories: &directories,
    };
    for (identity, (upstream, mut packages)) in groups {
        render_dependency_group(&mut context, &identity, upstream, &mut packages)?;
    }
    Ok(())
}

struct PackageRender<'a> {
    rendered: &'a mut String,
    config: &'a EffectiveConfig,
    graph: &'a ResolvedGraph,
    directories: &'a BTreeMap<String, String>,
}

fn dependency_groups(graph: &ResolvedGraph) -> BTreeMap<String, (bool, Vec<&ResolvedPackage>)> {
    let mut groups = BTreeMap::new();
    for package in graph.packages.iter().filter(|package| !package.first_party) {
        let (key, upstream) = group_identity(package);
        groups
            .entry(key)
            .or_insert_with(|| (upstream, Vec::new()))
            .1
            .push(package);
    }
    groups
}

fn group_identity(package: &ResolvedPackage) -> (String, bool) {
    package
        .repository
        .as_deref()
        .and_then(canonical_https_repository)
        .map(|value| (value, true))
        .unwrap_or_else(|| (package.id.clone(), false))
}

fn render_dependency_group(
    context: &mut PackageRender<'_>,
    identity: &str,
    upstream: bool,
    packages: &mut [&ResolvedPackage],
) -> Result<(), MaterialsError> {
    packages.sort_by(|left, right| {
        left.name
            .cmp(&right.name)
            .then_with(|| left.version.cmp(&right.version))
            .then_with(|| left.id.cmp(&right.id))
    });
    if upstream {
        context.rendered.push_str("\n## Upstream: `");
    } else {
        context.rendered.push_str("\n## Package identity: `");
    }
    context.rendered.push_str(&inline(identity));
    context.rendered.push_str("`\n");
    for package in packages {
        render_package(
            context.rendered,
            context.config,
            context.graph,
            package,
            context.directories,
        )?;
    }
    Ok(())
}

fn render_lockfiles(rendered: &mut String, graph: &ResolvedGraph) -> Result<(), MaterialsError> {
    let lockfiles = collect_lockfiles(graph)?;
    render_lockfile_table(rendered, lockfiles);
    Ok(())
}

fn collect_lockfiles(
    graph: &ResolvedGraph,
) -> Result<BTreeMap<String, LockfileEvidence>, MaterialsError> {
    let mut lockfiles = BTreeMap::new();
    for package in &graph.packages {
        collect_package_lockfiles(&mut lockfiles, package)?;
    }
    Ok(lockfiles)
}

fn collect_package_lockfiles(
    lockfiles: &mut BTreeMap<String, LockfileEvidence>,
    package: &ResolvedPackage,
) -> Result<(), MaterialsError> {
    for lockfile in &package.contributing_lockfiles {
        insert_lockfile(lockfiles, lockfile)?;
    }
    Ok(())
}

fn insert_lockfile(
    lockfiles: &mut BTreeMap<String, LockfileEvidence>,
    lockfile: &LockfileEvidence,
) -> Result<(), MaterialsError> {
    let entry = lockfiles
        .entry(lockfile.path.as_str().to_owned())
        .or_insert_with(|| lockfile.clone());
    if lockfile_conflicts(entry, lockfile) {
        return Err(MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid));
    }
    Ok(())
}

fn lockfile_conflicts(entry: &LockfileEvidence, lockfile: &LockfileEvidence) -> bool {
    entry.sha256 != lockfile.sha256 || entry.byte_len != lockfile.byte_len
}

fn render_lockfile_table(rendered: &mut String, lockfiles: BTreeMap<String, LockfileEvidence>) {
    if lockfiles.is_empty() {
        rendered.push_str("None.\n");
        return;
    }
    rendered.push_str("| Path |\n| --- |\n");
    for (path, _) in lockfiles {
        rendered.push_str("| `");
        rendered.push_str(&path);
        rendered.push_str("` |\n");
    }
}

fn render_package(
    rendered: &mut String,
    config: &EffectiveConfig,
    graph: &ResolvedGraph,
    package: &ResolvedPackage,
    directories: &BTreeMap<String, String>,
) -> Result<(), MaterialsError> {
    let (id_label, source_label) = config.package_field_labels(package);
    let relevant_edges = relevant_edges(graph, package);
    push_package_heading(rendered, package, id_label);
    push_package_role(rendered, &relevant_edges);
    push_dependency_kinds(rendered, &relevant_edges);
    push_target_conditions(rendered, &relevant_edges);
    render_optional(rendered, source_label, package.source.as_deref());
    render_optional(rendered, "Checksum", package.checksum.as_deref());
    render_optional(
        rendered,
        "Declared license",
        package.declared_license.as_deref(),
    );
    push_authors(rendered, package);
    render_optional(rendered, "Repository", package.repository.as_deref());
    render_optional(rendered, "Homepage", package.homepage.as_deref());
    push_contributing_lockfiles(rendered, package);
    render_retained_evidence(rendered, config, package, directories)
}

fn relevant_edges<'a>(
    graph: &'a ResolvedGraph,
    package: &ResolvedPackage,
) -> Vec<&'a DependencyEdge> {
    graph
        .edges
        .iter()
        .filter(|edge| edge.to_package_id == package.id)
        .collect()
}

fn push_package_heading(rendered: &mut String, package: &ResolvedPackage, id_label: &str) {
    rendered.push_str("\n### `");
    rendered.push_str(&inline(&package.name));
    rendered.push_str("` ");
    rendered.push_str(&inline(&package.version));
    rendered.push_str("\n\n- ");
    rendered.push_str(id_label);
    rendered.push_str(": `");
    rendered.push_str(&inline(&package.id));
    rendered.push_str("`\n- Role: ");
}

fn push_package_role(rendered: &mut String, edges: &[&DependencyEdge]) {
    rendered.push_str(if edges.iter().any(|edge| edge.direct) {
        "Direct"
    } else {
        "Transitive"
    });
}

fn push_dependency_kinds(rendered: &mut String, edges: &[&DependencyEdge]) {
    rendered.push_str("\n- Dependency kinds: ");
    let kinds = dependency_kind_labels(edges);
    if kinds.is_empty() {
        rendered.push_str("None.");
    } else {
        rendered.push_str(&kinds.join(", "));
    }
}

fn dependency_kind_labels(edges: &[&DependencyEdge]) -> Vec<&'static str> {
    let mut kinds = Vec::new();
    for (kind, label) in [
        (DependencyKind::Normal, "Normal"),
        (DependencyKind::Build, "Build"),
        (DependencyKind::Development, "Development"),
    ] {
        if edges.iter().any(|edge| edge.kind == kind) {
            kinds.push(label);
        }
    }
    kinds
}

fn push_target_conditions(rendered: &mut String, edges: &[&DependencyEdge]) {
    rendered.push_str("\n- Target conditions: ");
    let targets = edges
        .iter()
        .flat_map(|edge| edge.target_conditions.iter())
        .map(|target| inline(target))
        .collect::<BTreeSet<_>>();
    if targets.is_empty() {
        rendered.push_str("All targets.");
    } else {
        rendered.push_str(&joined_targets(&targets));
    }
}

fn joined_targets(targets: &BTreeSet<String>) -> String {
    targets
        .iter()
        .map(|target| format!("`{target}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn push_authors(rendered: &mut String, package: &ResolvedPackage) {
    rendered.push_str("\n- Authors: ");
    if package.authors.is_empty() {
        rendered.push_str("None.");
    } else {
        rendered.push_str(&joined_authors(package));
    }
}

fn joined_authors(package: &ResolvedPackage) -> String {
    package
        .authors
        .iter()
        .map(|author| inline(author))
        .collect::<Vec<_>>()
        .join("; ")
}

fn push_contributing_lockfiles(rendered: &mut String, package: &ResolvedPackage) {
    rendered.push_str("\n- Contributing lockfiles: ");
    if package.contributing_lockfiles.is_empty() {
        rendered.push_str("None.\n");
        return;
    }
    let paths = package
        .contributing_lockfiles
        .iter()
        .map(|lockfile| lockfile.path.as_str())
        .collect::<BTreeSet<_>>();
    rendered.push_str(&joined_paths(&paths));
    rendered.push('\n');
}

fn joined_paths(paths: &BTreeSet<&str>) -> String {
    paths
        .iter()
        .map(|path| format!("`{path}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_retained_evidence(
    rendered: &mut String,
    config: &EffectiveConfig,
    package: &ResolvedPackage,
    directories: &BTreeMap<String, String>,
) -> Result<(), MaterialsError> {
    rendered.push_str("\nRetained evidence:\n");
    if package.license_artifacts.is_empty() {
        rendered.push_str("- None.\n");
        return Ok(());
    }
    let directory = directories
        .get(&package.id)
        .ok_or_else(|| MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid))?;
    let basenames = evidence_basenames(package)?;
    if push_evidence_lines(rendered, config, package, directory, basenames) == 0 {
        rendered.push_str("- None.\n");
    }
    Ok(())
}

// The normalized graph does not prove provenance for a recovered artifact,
// so do not present its package-relative path as origin.
fn push_evidence_lines(
    rendered: &mut String,
    config: &EffectiveConfig,
    package: &ResolvedPackage,
    directory: &str,
    basenames: Vec<String>,
) -> usize {
    let mut rendered_evidence = 0;
    for (artifact, basename) in package.license_artifacts.iter().zip(basenames) {
        if is_supplemental_artifact(&basename) {
            continue;
        }
        rendered_evidence += 1;
        push_evidence_line(rendered, config, directory, &basename, &artifact.bytes);
    }
    rendered_evidence
}

fn push_evidence_line(
    rendered: &mut String,
    config: &EffectiveConfig,
    directory: &str,
    basename: &str,
    bytes: &[u8],
) {
    let evidence_path = format!(
        "{}/THIRD-PARTY-LICENSES/{directory}/{basename}",
        config.materials_directory().as_str()
    );
    let evidence_href = format!("THIRD-PARTY-LICENSES/{directory}/{basename}");
    rendered.push_str("- [`");
    rendered.push_str(&evidence_path);
    rendered.push_str("`](");
    rendered.push_str(&evidence_href);
    rendered.push_str(")\n  - SHA-256: `");
    rendered.push_str(&sha256_hex(bytes));
    rendered.push_str("`\n  - Bytes: ");
    rendered.push_str(&bytes.len().to_string());
    rendered.push('\n');
}

pub(crate) fn is_supplemental_artifact(basename: &str) -> bool {
    basename.eq_ignore_ascii_case("AHCL-EVIDENCE-SOURCE.md")
        || basename.eq_ignore_ascii_case("AHCL-MATERIALS.url")
}

fn render_optional(rendered: &mut String, label: &str, value: Option<&str>) {
    rendered.push_str("\n- ");
    rendered.push_str(label);
    rendered.push_str(": ");
    match value.filter(|value| !value.is_empty()) {
        Some(value) => {
            rendered.push('`');
            rendered.push_str(&inline(value));
            rendered.push('`');
        }
        None => rendered.push_str("None."),
    }
}

pub(crate) fn package_directories(graph: &ResolvedGraph) -> BTreeMap<String, String> {
    let inputs = graph
        .packages
        .iter()
        .filter(|package| !package.first_party)
        .map(|package| PackageDirectoryInput::new(&package.id, &package.name, &package.version))
        .collect::<Vec<_>>();
    assign_package_directories(&inputs)
}

pub(crate) fn evidence_basenames(package: &ResolvedPackage) -> Result<Vec<String>, MaterialsError> {
    let mut portable = BTreeSet::new();
    let mut basenames = Vec::new();
    for artifact in &package.license_artifacts {
        let basename = artifact
            .relative_path
            .as_str()
            .rsplit('/')
            .next()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid))?;
        validate_basename(basename)?;
        if !portable.insert(basename.to_ascii_lowercase()) {
            return Err(MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid));
        }
        basenames.push(basename.to_owned());
    }
    Ok(basenames)
}

pub(crate) fn validate_basename(value: &str) -> Result<(), MaterialsError> {
    if value.is_empty()
        || value == "."
        || value == ".."
        || value.contains(['/', '\\'])
        || ahcl_kit_core::RepoPath::parse(value).is_err()
    {
        return Err(MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid));
    }
    Ok(())
}

pub(crate) fn canonical_https_repository(value: &str) -> Option<String> {
    if repository_has_control_or_space(value) {
        return None;
    }
    let mut url = Url::parse(value).ok()?;
    if !https_url_with_host(&url) {
        return None;
    }
    normalize_repository_url(&mut url)
}

fn repository_has_control_or_space(value: &str) -> bool {
    value
        .chars()
        .any(|character| character.is_control() || character.is_whitespace())
}

fn https_url_with_host(url: &Url) -> bool {
    url.scheme() == "https" && url.host_str().is_some()
}

fn normalize_repository_url(url: &mut Url) -> Option<String> {
    let host = url.host_str()?.to_ascii_lowercase();
    url.set_host(Some(&host)).ok()?;
    let path = trimmed_repository_path(url.path());
    url.set_path(&path);
    Some(repository_string(url, path.is_empty()))
}

fn trimmed_repository_path(path: &str) -> String {
    let mut path = path.to_owned();
    if path.ends_with('/') {
        path.pop();
    }
    if path.ends_with(".git") {
        path.truncate(path.len().saturating_sub(4));
    }
    path
}

fn repository_string(url: &Url, path_empty: bool) -> String {
    let mut normalized = url.to_string();
    if path_empty && normalized.ends_with('/') {
        normalized.pop();
    }
    normalized
}

fn inline(value: &str) -> String {
    let mut rendered = String::new();
    for character in value.chars() {
        if character.is_control() {
            rendered.push(' ');
        } else {
            if character == '`' {
                rendered.push('\\');
            }
            rendered.push(character);
        }
    }
    rendered.trim().to_owned()
}
