// crates/ahcl-kit-materials/src/dependencies.rs - Dependency documentation generation.
//
// Copyright (C) 2026 Aperip Daedalus Foundation. All rights reserved.
//
// This file is part of AHCL Kit and is provided under version 1.1 of the
// Aperip Heimdall Commons License (AHCL). The applicable version is also subject
// to the AHCL provisions concerning Continuous AHCL Licensing Segments and
// migration to later official versions.
//
// After having a reasonable opportunity to read AHCL, all applicable Additional
// Restrictions, and all version notices, a person accepts the corresponding terms,
// to the extent permitted by applicable law, by using, copying, modifying, building,
// using this file as a dependency, deploying, distributing, or operating this file
// over a network.
//
// Official AHCL text and public notices:          https://ahcl.aperip.com
// AHCL Materials Directory:                       .ahcl/
// Repository official or recognized AHCL copy:   .ahcl/AHCL-1.1.md
// Project canonical repository:                   https://github.com/Aperip-Daedalus-Foundation/ahcl-kit
// AHCL origin and project notice:                 .ahcl/AHCL-PROJECT-NOTICE.md
// AHCL Version Adoption records:                  .ahcl/AHCL-VERSION-ADOPTION.md
// Complete Corresponding Source and history:      .ahcl/AHCL-SOURCE.md
// Dependencies, Referenced Materials, and licenses:
//                                                    .ahcl/AHCL-DEPENDENCIES.md
//
// SPDX-License-Identifier: LicenseRef-AHCL-1.1

use crate::{LayoutPolicy, MaterialsError, MaterialsErrorCode};
use ahcl_kit_cargo::{PackageDirectoryInput, assign_package_directories};
use ahcl_kit_config::{CargoLockMode, EffectiveConfig, Language};
use ahcl_kit_core::{
    ChangePlan, DependencyKind, LockfileEvidence, ProjectView, ResolvedGraph, ResolvedPackage,
};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use url::Url;

pub struct DependencyMaterialGenerator;

impl DependencyMaterialGenerator {
    pub fn plan_document(
        view: &dyn ProjectView,
        config: &EffectiveConfig,
        graph: &ResolvedGraph,
    ) -> Result<ChangePlan, MaterialsError> {
        let layout = LayoutPolicy::from_config(config)?;
        let mut desired = ChangePlan::new();
        desired
            .write(
                layout.dependencies_path()?,
                render_document(config, graph)?.into_bytes(),
            )
            .map_err(MaterialsError::from_plan)?;
        desired.compare(view).map_err(MaterialsError::from_plan)
    }
}

pub(crate) fn render_document(
    config: &EffectiveConfig,
    graph: &ResolvedGraph,
) -> Result<String, MaterialsError> {
    let layout = LayoutPolicy::from_config(config)?;
    let directories = package_directories(graph);
    let mut rendered =
        String::from("# AHCL Dependencies and Referenced Materials\n\nGenerated by AHCL Kit for ");
    rendered.push_str(&inline(config.project().name()));
    rendered.push_str(".\n\nConfiguration summary:\n- AHCL version: ");
    rendered.push_str(config.license().version().as_str());
    rendered.push_str("\n- Materials directory: `");
    rendered.push_str(layout.materials_directory().as_str());
    rendered.push_str("`\n- Ecosystem adapters: ");
    if config.languages().is_empty() {
        rendered.push_str("None.\n");
    } else {
        rendered.push_str(
            &config
                .languages()
                .iter()
                .map(|language| match language {
                    Language::Rust => "Rust",
                })
                .collect::<Vec<_>>()
                .join(", "),
        );
        rendered.push('\n');
    }
    rendered.push_str("- Cargo manifests: ");
    rendered.push_str(
        &config
            .rust()
            .cargo()
            .manifests()
            .iter()
            .map(|path| format!("`{}`", path.as_str()))
            .collect::<Vec<_>>()
            .join(", "),
    );
    rendered.push_str("\n- Cargo package selection: ");
    if config.rust().cargo().packages().is_empty() {
        rendered.push_str("All configured workspace roots.\n");
    } else {
        rendered.push_str(
            &config
                .rust()
                .cargo()
                .packages()
                .iter()
                .map(|package| format!("`{}`", inline(package)))
                .collect::<Vec<_>>()
                .join(", "),
        );
        rendered.push('\n');
    }
    rendered.push_str("- Cargo lock mode: ");
    rendered.push_str(match config.rust().cargo().lock_mode() {
        CargoLockMode::Locked => "locked",
    });
    rendered.push_str("\n- Strict license files: ");
    rendered.push_str(if config.generation().strict_license_files() {
        "true"
    } else {
        "false"
    });
    rendered.push_str("\n\n## Contributing Lockfiles\n\n");
    render_lockfiles(&mut rendered, graph)?;

    let mut groups: BTreeMap<String, (bool, Vec<&ResolvedPackage>)> = BTreeMap::new();
    for package in graph.packages.iter().filter(|package| !package.first_party) {
        let repository = package
            .repository
            .as_deref()
            .and_then(canonical_https_repository);
        let (key, upstream) = repository
            .map(|value| (value, true))
            .unwrap_or_else(|| (package.id.clone(), false));
        groups
            .entry(key)
            .or_insert_with(|| (upstream, Vec::new()))
            .1
            .push(package);
    }

    if groups.is_empty() {
        rendered.push_str("\n## Dependencies and Referenced Materials\n\nNone.\n");
    } else {
        for (identity, (upstream, mut packages)) in groups {
            packages.sort_by(|left, right| {
                left.name
                    .cmp(&right.name)
                    .then_with(|| left.version.cmp(&right.version))
                    .then_with(|| left.id.cmp(&right.id))
            });
            if upstream {
                rendered.push_str("\n## Upstream: `");
            } else {
                rendered.push_str("\n## Package identity: `");
            }
            rendered.push_str(&inline(&identity));
            rendered.push_str("`\n");
            for package in packages {
                render_package(&mut rendered, config, graph, package, &directories)?;
            }
        }
    }
    rendered.push_str(
        "\nAHCL Kit reports declared metadata and retained evidence without selecting or interpreting legal terms.\n",
    );
    Ok(rendered)
}

fn render_lockfiles(rendered: &mut String, graph: &ResolvedGraph) -> Result<(), MaterialsError> {
    let mut lockfiles: BTreeMap<String, (LockfileEvidence, BTreeSet<String>)> = BTreeMap::new();
    for package in &graph.packages {
        for lockfile in &package.contributing_lockfiles {
            let entry = lockfiles
                .entry(lockfile.path.as_str().to_owned())
                .or_insert_with(|| (lockfile.clone(), BTreeSet::new()));
            if entry.0.sha256 != lockfile.sha256 || entry.0.byte_len != lockfile.byte_len {
                return Err(MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid));
            }
            entry.1.insert(package.id.clone());
        }
    }
    if lockfiles.is_empty() {
        rendered.push_str("None.\n");
        return Ok(());
    }
    rendered
        .push_str("| Path | SHA-256 | Bytes | Resolved packages |\n| --- | --- | ---: | ---: |\n");
    for (_, (lockfile, packages)) in lockfiles {
        rendered.push_str("| `");
        rendered.push_str(lockfile.path.as_str());
        rendered.push_str("` | `");
        rendered.push_str(&lockfile.sha256);
        rendered.push_str("` | ");
        rendered.push_str(&lockfile.byte_len.to_string());
        rendered.push_str(" | ");
        rendered.push_str(&packages.len().to_string());
        rendered.push_str(" |\n");
    }
    Ok(())
}

fn render_package(
    rendered: &mut String,
    config: &EffectiveConfig,
    graph: &ResolvedGraph,
    package: &ResolvedPackage,
    directories: &BTreeMap<String, String>,
) -> Result<(), MaterialsError> {
    rendered.push_str("\n### `");
    rendered.push_str(&inline(&package.name));
    rendered.push_str("` ");
    rendered.push_str(&inline(&package.version));
    rendered.push_str("\n\n- Cargo package ID: `");
    rendered.push_str(&inline(&package.id));
    rendered.push_str("`\n- Role: ");
    let relevant_edges = graph
        .edges
        .iter()
        .filter(|edge| edge.to_package_id == package.id)
        .collect::<Vec<_>>();
    rendered.push_str(if relevant_edges.iter().any(|edge| edge.direct) {
        "Direct"
    } else {
        "Transitive"
    });
    rendered.push_str("\n- Dependency kinds: ");
    let mut kinds = Vec::new();
    for (kind, label) in [
        (DependencyKind::Normal, "Normal"),
        (DependencyKind::Build, "Build"),
        (DependencyKind::Development, "Development"),
    ] {
        if relevant_edges.iter().any(|edge| edge.kind == kind) {
            kinds.push(label);
        }
    }
    if kinds.is_empty() {
        rendered.push_str("None.");
    } else {
        rendered.push_str(&kinds.join(", "));
    }
    rendered.push_str("\n- Target conditions: ");
    let targets = relevant_edges
        .iter()
        .flat_map(|edge| edge.target_conditions.iter())
        .map(|target| inline(target))
        .collect::<BTreeSet<_>>();
    if targets.is_empty() {
        rendered.push_str("All targets.");
    } else {
        rendered.push_str(
            &targets
                .iter()
                .map(|target| format!("`{target}`"))
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
    render_optional(rendered, "Cargo source", package.source.as_deref());
    render_optional(rendered, "Checksum", package.checksum.as_deref());
    render_optional(
        rendered,
        "Declared license",
        package.declared_license.as_deref(),
    );
    rendered.push_str("\n- Authors: ");
    if package.authors.is_empty() {
        rendered.push_str("None.");
    } else {
        rendered.push_str(
            &package
                .authors
                .iter()
                .map(|author| inline(author))
                .collect::<Vec<_>>()
                .join("; "),
        );
    }
    render_optional(rendered, "Repository", package.repository.as_deref());
    render_optional(rendered, "Homepage", package.homepage.as_deref());
    rendered.push_str("\n- Contributing lockfiles: ");
    if package.contributing_lockfiles.is_empty() {
        rendered.push_str("None.\n");
    } else {
        let paths = package
            .contributing_lockfiles
            .iter()
            .map(|lockfile| lockfile.path.as_str())
            .collect::<BTreeSet<_>>();
        rendered.push_str(
            &paths
                .iter()
                .map(|path| format!("`{path}`"))
                .collect::<Vec<_>>()
                .join(", "),
        );
        rendered.push('\n');
    }
    rendered.push_str("\nRetained evidence:\n");
    if package.license_artifacts.is_empty() {
        rendered.push_str("- None.\n");
        return Ok(());
    }
    let directory = directories
        .get(&package.id)
        .ok_or_else(|| MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid))?;
    let basenames = evidence_basenames(package)?;
    for (artifact, basename) in package.license_artifacts.iter().zip(basenames) {
        let evidence_path = format!(
            "{}/THIRD-PARTY-LICENSES/{directory}/{basename}",
            config.materials_directory().as_str()
        );
        let evidence_href = format!("THIRD-PARTY-LICENSES/{directory}/{basename}");
        rendered.push_str("- [`");
        rendered.push_str(&evidence_path);
        rendered.push_str("`](");
        rendered.push_str(&evidence_href);
        rendered.push_str(")\n  - SHA-256: `");
        rendered.push_str(&sha256_hex(&artifact.bytes));
        rendered.push_str("`\n  - Bytes: ");
        rendered.push_str(&artifact.bytes.len().to_string());
        rendered.push_str("\n  - Package origin: `");
        rendered.push_str(artifact.relative_path.as_str());
        rendered.push_str("`\n");
    }
    Ok(())
}

fn render_optional(rendered: &mut String, label: &str, value: Option<&str>) {
    rendered.push_str("\n- ");
    rendered.push_str(label);
    rendered.push_str(": ");
    match value.filter(|value| !value.is_empty()) {
        Some(value) => {
            rendered.push('`');
            rendered.push_str(&inline(value));
            rendered.push('`');
        }
        None => rendered.push_str("None."),
    }
}

pub(crate) fn package_directories(graph: &ResolvedGraph) -> BTreeMap<String, String> {
    let inputs = graph
        .packages
        .iter()
        .filter(|package| !package.first_party)
        .map(|package| PackageDirectoryInput::new(&package.id, &package.name, &package.version))
        .collect::<Vec<_>>();
    assign_package_directories(&inputs)
}

pub(crate) fn evidence_basenames(package: &ResolvedPackage) -> Result<Vec<String>, MaterialsError> {
    let mut portable = BTreeSet::new();
    let mut basenames = Vec::new();
    for artifact in &package.license_artifacts {
        let basename = artifact
            .relative_path
            .as_str()
            .rsplit('/')
            .next()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid))?;
        validate_basename(basename)?;
        if !portable.insert(basename.to_ascii_lowercase()) {
            return Err(MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid));
        }
        basenames.push(basename.to_owned());
    }
    Ok(basenames)
}

pub(crate) fn validate_basename(value: &str) -> Result<(), MaterialsError> {
    if value.is_empty()
        || value == "."
        || value == ".."
        || value.contains(['/', '\\'])
        || ahcl_kit_core::RepoPath::parse(value).is_err()
    {
        return Err(MaterialsError::new(MaterialsErrorCode::ManagedTreeInvalid));
    }
    Ok(())
}

pub(crate) fn canonical_https_repository(value: &str) -> Option<String> {
    if value
        .chars()
        .any(|character| character.is_control() || character.is_whitespace())
    {
        return None;
    }
    let mut url = Url::parse(value).ok()?;
    if url.scheme() != "https" || url.host_str().is_none() {
        return None;
    }
    let host = url.host_str()?.to_ascii_lowercase();
    url.set_host(Some(&host)).ok()?;
    let mut path = url.path().to_owned();
    if path.ends_with('/') {
        path.pop();
    }
    if path.ends_with(".git") {
        path.truncate(path.len().saturating_sub(4));
    }
    url.set_path(&path);
    let mut normalized = url.to_string();
    if path.is_empty() && normalized.ends_with('/') {
        normalized.pop();
    }
    Some(normalized)
}

pub(crate) fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut result = String::with_capacity(64);
    for byte in digest {
        use std::fmt::Write;
        let _ = write!(result, "{byte:02x}");
    }
    result
}

fn inline(value: &str) -> String {
    let mut rendered = String::new();
    for character in value.chars() {
        if character.is_control() {
            rendered.push(' ');
        } else {
            if character == '`' {
                rendered.push('\\');
            }
            rendered.push(character);
        }
    }
    rendered.trim().to_owned()
}
